### ISSUE TITLE
NEXT button on checkout not working

### ISSUE THREAD

**Issue by andrewdyson3** [concrete5-community-store/community_store#368]
NEXT button on checkout not working only on mobile devices. Works on a desktop. Any other reports of this not working on mobile devices? How can I go about troubleshooting this?

**Comment by typoman76** [comment]
Hey @andrewdyson3
I have no issues on next buttons. I run 2 stores actually. 
Perhaps there is a conflict in your javascript. Do you have a link? On which specific mobile device does that happen?
Best regards, Roland

**Comment by andrewdyson3** [comment]
Yes please have a look at www.dysonian.com android and ios devices safari and also on firefox have the issue. You can shop pick something select checkout as guest put in a name address ect then try and click NEXT its doesnt function. Thanks

**Comment by typoman76** [comment]
From my first look. I think that an element overlaps the button. 
Will have a look later. On the road now.

**Comment by AdamBassett** [comment]
This is an issue with elements overlapping and blocking the click through. See issue [337](https://github.com/concrete5-community-store/community_store/issues/337).  Try updating your code to the newest release of community-store.

**Comment by andrewdyson3** [comment]
Ah ok I searched and couldnt find that work was done on the issue. Um whats the proper way to update my community store with out messing anything else up? This is a live site. Thanks

**Comment by AdamBassett** [comment]
Well my first suggestion would be to copy the live site to a beta location and make your changes there and test then push the beta up to live.  You should never dev on a live site.

As far as updating the code.  You should be able to pull down the latest version from Github and simply replace the folder in your packages folder.  This is assuming that you have not modified anything in the community store folder.

**Comment by typoman76** [comment]
It's a good idea to get to the latest store version. But as Adam said try it under a development environment. 
In the meanwhile you could use some css to solve the problem by adding this line. E.g. to your theme css.

`.store-checkout-form-group-buttons { height: 40px }`

This gives a height to the button area and the overlapping is gone.

**Comment by andrewdyson3** [comment]
Not modified? I have products there?

**Comment by andrewdyson3** [comment]
Thank you very much I got it working....!!!! I just added this line to the checkout css.
.store-checkout-form-group-buttons { height: 40px }
Seamed to be the easiest thing to do...

**Comment by andrewdyson3** [comment]
Well the 40px worked on my Galaxy 9+ but on iphones it still has the issue. Is there another easy suggestion?

.store-checkout-form-group-buttons { height: 40px }

**Comment by typoman76** [comment]
Hey andrewdyson3 – I visited your store and did an inspection. The css is not applied. So something went wrong on your fixing.
a) Did you clear the cache? http://www.dysonian.com/dashboard/system/optimization/clearcache
b) Where did you exactly added this? A file path would help me understand your structure.

And you should still consider to do an update on a development environment like Adam Bassett suggested. This is just a temporary fix with css. The new community_store version will also fix some other issues that could happen on your store. 

best regards, Roland

**Comment by andrewdyson3** [comment]
I put it in community-store.css

/* Checkout Page Component Visibility */
.store-checkout-form-group-buttons { height: 40px }
.store-checkout-form-group-body {
    display: none;
}

Here is the path

dysonian/packages/community_store/css/
--

**Comment by andrewdyson3** [comment]
Is my issue still active?

**Comment by Mesuva** [comment]
I'm pretty sure this original issue was fixed in community store at some point, so you're welcome to close this issue if you think there is nothing left to address.

**Comment by andrewdyson3** [comment]
Well I answered the question to me with this and didnt receive a response from Roland


I put it in community-store.css

/* Checkout Page Component Visibility */
.store-checkout-form-group-buttons { height: 40px }
.store-checkout-form-group-body {
display: none;
}

Here is the path
dysonian/packages/community_store/css/



I still have the issue on iphones.

**Comment by typoman76** [comment]
Hey @andrewdyson3
The fix is working. Tested this with 2 iPhones. 
You should clear the cache on your test phone for safari. 
Best regards, Roland

**Comment by andrewdyson3** [comment]
Thanks Roland I appreciate you having a look.
I am still lost as to how to upgrade to the latest release. Its been a while and i was doing so much to get the site up and running I cant recall what all I did to get it working. I did do some tweaks to get some things working. I tried several different options and now its all just a blur in my memory.

**Comment by Mesuva** [comment]
The only thing I can suggest here is to take a full clone of your site and try an upgrade on that.
If you are doing tweaks, like the concrete5 core you should always be looking for ways to modify things without directly editing the package - by overriding block and single page templates.
